name: Build and Push to Deploy Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Push build to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Save build output temporarily
          mv build build-temp

          # Create clean orphan branch
          git checkout --orphan deploy
          git reset --hard
          rm -rf *

          # Move build files back in
          mv build-temp/* .

          # Commit and push
          git add .
          git commit -m "🚀 Auto-deploy: $(date)"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:deploy --force
